# Generated by Django 3.2.5 on 2022-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=45)),
                ('rdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
