# Generated by Django 4.0.6 on 2022-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.EmailField(max_length=60)),
                ('comment', models.TextField()),
                ('rdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
